### ISSUE TITLE
[Feature request] expose timeout const

### ISSUE THREAD

**Issue by WaSheep** [1904labs/dom-to-image-more#11]
### Use case: description, code  

[jsfiddle](https://jsfiddle.net/IDisposable/emjL1ow8/)

### Browsers

- [ ] Chrome 49+  
- [ ] Firefox 45+  
![image](https://user-images.githubusercontent.com/17945318/61218845-8bb52f80-a745-11e9-8022-b7095bbacf2a.png)

**Comment by IDisposable** [comment]
Released in v.2.9.4
