### ISSUE TITLE
Font distorted in downloaded image

### ISSUE THREAD

**Issue by mmohamud1** [1904labs/dom-to-image-more#118]
# Use case: description, code
Hi so I'm using this tool to export a dashboard as an image and I've noticed when I use "font-family: proxima-nova, sans-serif;" for card headings the header is distorted where as the rest of the dashboard looks fine, I have experimented by changing fonts and it looks fine. Any help would be greatly appreciated

![AWS](https://user-images.githubusercontent.com/63135402/222178710-6ce88970-e040-4155-862d-7888f669c045.png)

**Comment by IDisposable** [comment]
Did this work correctly in the 3.x releases?
