### ISSUE TITLE
domtoImage converts only first child element when cloneNode(true) is used

### ISSUE THREAD

**Issue by surbhi-software** [1904labs/dom-to-image-more#169]
Hello,

I am trying to convert the complex html page to PNG and SVG. I want to modify few elements or may be add few more to the cloned element and then convert the whole complex element. Now the problem is coming when I use cloneNode(true) and try to pass the variable to domtoimage.toPNG(container). The cloneNode is only sending the first child and not the whole container. Is this a bug or am I missing anything here?

**Comment by IDisposable** [comment]
This **will not work** if you are (outside/before) cloning the node yourself, that cloned node _does not automatically have all the children_ (this is normal DOM behavior, and the reason most of this code exists!).

If possible, pass the original node to be converted.
