### ISSUE TITLE
Unavaible to override existing CSS style within the adjustClone function

### ISSUE THREAD

**Issue by chege1805** [1904labs/dom-to-image-more#170]
It is not possible  to override an existing CSS style in the adjustClone function.

[jsfiddle](https://jsfiddle.net/42cyghsu/6/) https://jsfiddle.net/42cyghsu/6/

## Expected behavior
The generated PDF apply the styles set in the adjustClone function
## Actual behavior (stack traces, console logs etc)
Only unset CSS style is visible in the output PDF
## Browsers
ALL

**Comment by IDisposable** [comment]
Thank you for the JSFiddle!

Looks like it's indeed a bug... one thing I noticed, though... you should NOT be checking the `clone.id` as that should be getting assigned a different value on the clone can't have two DOM nodes with the same `.id`). Check the `node.id` instead... but I doubt that's your issue... will track this down

**Comment by Prithviraj-kf** [comment]
Facing the same problem. 
Even after adding a style to the clone using adjustClonedNode it is getting replaced by the source element styles.  

Do we have any workaround for this use case ? @IDisposable @chege1805 

<img width="855" alt="image" src="https://github.com/1904labs/dom-to-image-more/assets/84726594/53c73eb6-458d-41f6-ab22-b2779100e56f">

**Comment by codesculpture** [comment]
By the help of @Prithviraj-kf, we believe this could be solved by this https://github.com/1904labs/dom-to-image-more/pull/175
@chege1805

**Comment by codesculpture** [comment]
This is fixed and released in 3.3.1 @chege1805 @Prithviraj-kf 

Can be closed.
