### ISSUE TITLE
Date Inputs Not Captured in Firefox (v127.0)

### ISSUE THREAD

**Issue by nblixt** [1904labs/dom-to-image-more#171]
# Use case: description, code
Hello.  Thank you for maintaining this library.

When attempting to capture an input with a date type in Firefox, the field appears blank.  This does not happen in Safari or Chrome.

[jsfiddle](https://jsfiddle.net/903wnr72/1/)

JS code in app:
```
  let captureNode = document.getElementById('capture')
  let captureNodePositionInfo = captureNode.getBoundingClientRect()
  let blob = domtoimage.toBlob(
    captureNode,
    {
      width: captureNodePositionInfo.width,
      height: captureNodePositionInfo.height,
      bgcolor: 'white'
    }
  )
```

## Expected behavior
Values in `<input type="date">` are captured in the image in Firefox.

## Actual behavior (stack traces, console logs etc)
Values in `<input type="date">` are not captured in the image in Firefox.

I do not see any errors in the console when I do this.

## Library version
3.3.0

## Browsers
Affected:
- Firefox v127.0

Unaffected:
- Chrome v125.0.6422.142
- Safari v17.5

**Comment by IDisposable** [comment]
Seems working on 3.4.0 https://jsfiddle.net/wbf4Lstu/1/
