### ISSUE TITLE
When an image is rendered in the Dom of SVG, it is lost when exported

### ISSUE THREAD

**Issue by cMing1997** [1904labs/dom-to-image-more#172]
# Use case: description, code

## Expected behavior

Exports all elements in a given Dom

![image](https://github.com/1904labs/dom-to-image-more/assets/40878104/86699eba-e68e-4666-8673-9d04da917f53)

## Actual behavior (stack traces, console logs etc)
There is no export for the image element

![image](https://github.com/1904labs/dom-to-image-more/assets/40878104/f76880c3-8c99-483d-90cd-a01b56b8afaf)

## Library version
3.3.0

## Browsers

-   [X] Edge  125.0.2535.67
-   [ ] Firefox 45+

**Comment by cMing1997** [comment]
The Final Solution

Use the HTML IMG tag instead of the Image Tag in the SVG

**Comment by IDisposable** [comment]
Thanks for the follow up solution
