### ISSUE TITLE
在mac的Retina屏上面，截图不全

### ISSUE THREAD

**Issue by jdhaddy** [1904labs/dom-to-image-more#177]
采用的vue框架，采用domtoimage.toPng方法进行截图，在Mac的Retina屏（3072x1920）上截图不全，高度和宽度都不符合。当移动到扩展屏（1920x1080）上截图正确。

**Comment by IDisposable** [comment]
I regret to say that I can only understand English.

**Comment by jdhaddy** [comment]
Thank you for your reply. On the screen with resolution of 1920x1080, the screenshot is correct, but when the same code is on the Retina screen of Mac with resolution of (3072x1920), the screenshot is only partial and incomplete.
The results are as follows: the expected screenshot result is the above picture, and the wrong screenshot result is the following picture.Looking forward to your reply, thank you very much.
<img width="981" alt="image" src="https://github.com/user-attachments/assets/5613c855-4357-497f-8131-e60215b3d6ed">
<img width="971" alt="image" src="https://github.com/user-attachments/assets/6758c416-dd6e-4a01-a740-bf183980b1e9">
