### ISSUE TITLE
Since v3.0.1-rc.0 the created image is not fully capturing the site

### ISSUE THREAD

**Issue by func0der** [1904labs/dom-to-image-more#180]
# Use case: 
Since version 3.0.1-rc.0 there is only a part of the dom captured.
https://github.com/1904labs/dom-to-image-more/compare/v3.0.0-rc1...v3.0.1-rc.0

I am not sure how to reproduce this outside of our application.

## Expected behavior
Captures full dom content

## Actual behavior (stack traces, console logs etc)
Captures only a small part 
![image](https://github.com/user-attachments/assets/22a13db1-40cd-461a-a9d2-ffaefbc4a3ed)

## Library version
v3.0.1-rc.0

## Browsers

-   [ x] Chrome 49+
-   [x ] Firefox 45+

**Comment by IDisposable** [comment]
There's LITERALLY no way I can help you fix this without some actual HTML/CSS. Please resubmit with at least a JSFiddle
