### ISSUE TITLE
dom-to-image-more only captures part of the DOM content

### ISSUE THREAD

**Issue by iLoveBug** [1904labs/dom-to-image-more#197]
Description:

I am using dom-to-image-more to convert a DOM element into an image, but the output image only contains a portion of the DOM content, not the entire element. Please find the attached test files (test.html and result.png) for reference. The HTML file includes the DOM structure I'm trying to capture, and the PNG file shows the incomplete result.

Steps to Reproduce:

Use the dom-to-image-more library to convert a DOM element into an image.
Run the provided test HTML file.
Observe that the generated image only captures part of the content, rather than the full DOM element.
Expected Behavior:

The output image should contain the entire content of the specified DOM element.

Actual Behavior:

The output image only contains a portion of the DOM content.

Environment:

Browser: (safari 18.1, Mac OS 15.1 and Safari on mobile, IOS 18.0.1)
dom-to-image-more version: (3.5.0)
Attachments:

The test code:

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://unpkg.com/dom-to-image-more@3.5.0/dist/dom-to-image-more.min.js"></script>
  <title>DOM to Image Example</title>
  <style>
    #box {
      width: 500px;
      height: 700px;
      scale: 0.7;
    }

    #my-node {
      width: 100%;
      height: 100%;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      border: 1px solid #ccc;
      border-radius: 5px;
      color: rgb(226, 43, 70);
    }
  </style>
</head>

<body>
  <div id="box">
    <div id="my-node">
      <h1>Hello World</h1>
      <p>This is an example of using dom-to-image-more.</p>
    </div>
  </div>
  <button id="download">Download Image</button>

  <script>
    let node = document.getElementById('my-node');
    const imageUrl = 'https://images.unsplash.com/photo-1719937206667-ac87c15ad3e9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'

    node.style.backgroundImage = `url(${imageUrl})`;

    document.getElementById('download').addEventListener('click', function () {
      domtoimage.toPng(node, {
        quality: 0.9,
        copyDefaultStyles: false
      })
        .then(function (dataUrl) {
          let link = document.createElement('a');
          link.download = 'my-image.png';
          link.href = dataUrl;
          link.click();
        })
        .catch(function (error) {
          console.error('oops, something went wrong!', error);
        });
    });
  </script>

</body>

</html>

result.png: The resulting image showing the issue
![result](https://github.com/user-attachments/assets/c925ea4f-2e64-438e-8487-7770d2dcc6c5)

**Comment by IDisposable** [comment]
Did you find a resolution? Care to share with others what you changed?

**Comment by iLoveBug** [comment]
Not yet. Is there anybody has the same problem?

Sent from my  iPhone

> 在 2024年10月31日，23:12，Marc Brooks ***@***.***> 写道：
> 
> Did you find a resolution? Care to share with others what you changed?
