### ISSUE TITLE
bower  package not found

### ISSUE THREAD

**Issue by leetmachine** [1904labs/dom-to-image-more#2]
tried to install with bower install dom-to-image-more but was unsuccessful.

bower error: ENOTFOUND Package dom-to-image-more not found.

**Comment by IDisposable** [comment]
Sorry about that... Bower refuses to let me login correctly. Can you use the NPM version?

**Comment by IDisposable** [comment]
I've attempted to publish to Bower today, but not showing in the search yet.

**Comment by IDisposable** [comment]
Bower finally let me login and publish. Thanks for reporting the issue.
