### ISSUE TITLE
Fails to export elements with 0 width

### ISSUE THREAD

**Issue by AidasK** [1904labs/dom-to-image-more#3]
### Use case: description, code  

Fails to export canvas with 0 width
[https://jsfiddle.net/nv5aq6wh/](https://jsfiddle.net/nv5aq6wh/)
![image](https://user-images.githubusercontent.com/2088484/56146780-86faa700-5faf-11e9-801d-34b031f927fe.png)

### Expected behavior
export image

### Actual behavior (stack traces, console logs etc)
throws error without stacktrace and explanation. was hard to find a cause...

### Library version
@master

### Browsers

- [x] Chrome 49+

**Comment by AidasK** [comment]
I am using this library to export @openlayers map as shown in https://openlayers.org/en/master/examples/export-map.html
But sometimes openlayers adds an empty canvas to the dom and this lib crashes

**Comment by IDisposable** [comment]
Do you have a test for this already or should I craft one?

**Comment by AidasK** [comment]
No, I havent launched tests for this. Please do if you can

**Comment by IDisposable** [comment]
Test added, released as v2.7.6. Thank you for your contribution.
