### ISSUE TITLE
Release Request: Add onclone feature as a new release

### ISSUE THREAD

**Issue by Daniel199438** [1904labs/dom-to-image-more#31]
Hey first of all: Great work! 

I want to ask you if you could release a new version to npm/yarn with your changes from the last months. 
Escpecially the onclone feature is something I need for my project. 

Thank you in advance! :)

**Comment by IDisposable** [comment]
Yes, I  am out of town until next week, then I will push out a new version

**Comment by IDisposable** [comment]
Releasing a new version on Thursday

**Comment by Daniel199438** [comment]
okay dokay

**Comment by IDisposable** [comment]
Released v2.9.4 today
