### ISSUE TITLE
Render to image without having to append to DOM Tree

### ISSUE THREAD

**Issue by chitgoks** [1904labs/dom-to-image-more#32]
Is this possible?

I have been using this but it is limited to having to ensure the element is already in the DOM Tree.

Mu use case, is that there are times i create the element programmatically. Thing is, I have to attach this to the DOM tree in order for the toSvg() or toPng() to work.

I wonder if it is possible to do the same thing without having to add the element to the DOM tree?

```
    var el = document.createElement('div');
    el.setAttribute('style', 'white-space: nowrap; position: relative; z-index: -99; width: 100px; height:200px; display: inline-block; font: ' 12px Arial');
    el.setAttribute('id', 'test');
    el.innerHTML = 'sample text';

    $('#where_to_insert).append(el);

    domtoimage.toSvg(el).then(function(dataUrl) {
console.log(dataUrl);
        $(el).remove();
    });
```

This works because of     $('#where_to_insert).append(el);, but if i do not add it to the DOM Tree. nothing gets rendered.

Thoughts?

**Comment by gioele-antoci** [comment]
Can't you render it offscreen?

**Comment by chitgoks** [comment]
Ill close this. i found a workaround.

**Comment by gioele-antoci** [comment]
I am curious, what was the workaround ? (it might help someone else stumbling onto this)

**Comment by chitgoks** [comment]
i just attached it to another dom that is not visible to the user on screen.

seems the issue i had was because the dom does not exist, so nothing gets
rendered. so i attached it to a dom that always exists but not visible to
the user
