### ISSUE TITLE
merge from dom-to-image

### ISSUE THREAD

**Issue by jarnovanrhijn** [1904labs/dom-to-image-more#5]
Hi,

is it possible to merge https://github.com/tsayen/dom-to-image/pull/142 or has it already been done?

Thanks in advance!!

**Comment by IDisposable** [comment]
Working on that now, thanks for asking! :)

**Comment by jarnovanrhijn** [comment]
Thanks for replying 😁

**Comment by QingWei-Li** [comment]
Any progress?

**Comment by michael13491** [comment]
@IDisposable any update on this? it does not look like tsayen#142 has been merged yet.

**Comment by IDisposable** [comment]
Should now be working (fully merged) in v2.9.3
