### ISSUE TITLE
Cannot take screenshot of more complex webpages

### ISSUE THREAD

**Issue by joswhite** [1904labs/dom-to-image-more#70]
### Use case:

I'm trying to take a png screenshot using dom-to-image-more for more complex web pages (6000+ HTML nodes), using Firefox version 100.

As an example, see https://jsfiddle.net/joseph_white3/gj7v21yz/.

### Expected behavior

Screenshot should be taken successfully. Webpages of this size are quite common, for example Google Sheets has 5000-6000 HTML nodes, according to the output of `document.getElementsByTagName('*').length`.

### Actual behavior

In Chrome version 101, the code works fine. In Firefox 100 though, `domtoimage.toPng` throws an error in the makeImage function [line 555](https://github.com/1904labs/dom-to-image-more/blob/master/src/dom-to-image-more.js#L555):

![image](https://user-images.githubusercontent.com/7979277/167205394-f2fe6efd-44f7-4d89-802e-3b96460e53f7.png)

Note: JSFiddle is letting the page crash instead of logging the error. I had to copy the HTML to a separate webpage to inspect the error.

Presumably this occurs because the data `uri` is a string 34277656 characters long (32.7 MB), which exceeds the max data URI length (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs#common_problems), which states that Firefox 97+ has a max data URI length of 32 MB). As a result, the `image.onerror` function in `makeImage` gets called with the error shown above.

### Library version

Latest (v. 2.9.5)

### Browsers

- [] Chrome 49+
- [x] Firefox 45+

**Comment by meche-gh** [comment]
Could you update [this SO comment](https://stackoverflow.com/questions/22907735/get-the-computed-style-and-omit-defaults/56408175#comment127572094_40814529) to "maybe" recommend [`filterWinningInlineStyles` HPF as a post-processing op](https://github.com/1904labs/dom-to-image-more/issues/92#issuecomment-1361552316)?`copyUserComputedStyle` is an overeager data reduction.

If the library adopts `filterWinningInlineStyles` it will be necessary to put the SVG root in the sandbox iframe, then take the iframe width and height straight from the SVG.

**Comment by joswhite** [comment]
I think by "post-processing op", you mean running styles through `copyUserComputedStyleFast` as a first pass, then the remainder through the block of code you posted above, right? That would result in the best performance.

Thanks for giving a shot at implementing this!

I did post an extra comment on StackOverflow. However, I cannot recommend this approach due to the complexity of the algorithm (see my comment in https://github.com/1904labs/dom-to-image-more/issues/92).

**Comment by meche-gh** [comment]
> I think by "post-processing op", you mean running styles through `copyUserComputedStyleFast` as a first pass, then the remainder through the block of code you linked to above, right? That would result in the best performance.

Correct!

**Comment by meche-gh** [comment]
I noticed that for `toSvg(node, options)`, the sandbox is not removed, and the default styles cache is not cleared after 20s.  
Is persisting the default styles cache of benefit?  
(Polluting the DOM with 1 `<iframe>` per SVG screenshot is a bug of course.)

**Comment by IDisposable** [comment]
Seems to work fine with current source inlined in this fiddle https://jsfiddle.net/L4bdynwr/

**Comment by joswhite** [comment]
You are correct. `removeSandbox` is called in `draw()`, which calls `toSvg()`. `toSvg()` does not call `removeSandbox`. We need to move the `removeSandbox` call from `draw()` into `toSvg()`.

**Comment by IDisposable** [comment]
Sorry, that  leak has been corrected in v2.14.1 and v3.0.2-rc.0
