### ISSUE TITLE
NPM package should not contain bower_components

### ISSUE THREAD

**Issue by ddolcimascolo** [1904labs/dom-to-image-more#74]
### Use case: description, code  

Package usage via _NPM_

### Expected behavior

Installed package does not contain `bower_components`

### Actual behavior (stack traces, console logs etc)

Package contains `bower_components`

### Library version

Latest (2.10.1)

**Comment by ddolcimascolo** [comment]
Hi guys,

Thx for the good work in maintaing this fork. We use it happily :)
As a side note regarding the resolution of this issue, I think you can safely drop `bower` support completely in 2022. Is anyone still using it nowadays?

If you still want to support bower, can you simply add a `.npmignore` file to exclude `bower_compoonents` ?

Cheers,
David

**Comment by IDisposable** [comment]
A very good point, I think it's time as well.

**Comment by IDisposable** [comment]
How does https://github.com/1904labs/dom-to-image-more/pull/75 look to you?

**Comment by ddolcimascolo** [comment]
Looks good. From a semver perspective this could technically be considered a breaking change, though I doubt anyone's installing your lib through bower...

Looking forward to installing the new version!

David

**Comment by ddolcimascolo** [comment]
@IDisposable Any plan to release this?

**Comment by IDisposable** [comment]
Done! https://github.com/1904labs/dom-to-image-more/releases/tag/v2.11.1
