### ISSUE TITLE
Optimize requests of webfonts

### ISSUE THREAD

**Issue by imatwork** [1904labs/dom-to-image-more#79]
Downloaded the latest, and it looks like https://github.com/tsayen/dom-to-image/issues/37 from `dom-to-image` is not fixed (it's not fixed in `dom-to-image` either). There is an open PR in the original repo though, https://github.com/tsayen/dom-to-image/pull/336

I tried it with the latest of `dom-to-image-more` and the below looks like the requests that occur

![image](https://user-images.githubusercontent.com/95493333/188719359-8a201f9e-6389-4213-831a-24691eb7aba0.png)

**Comment by IDisposable** [comment]
Release as 2.12.0... thanks for the note and pointing me at a solution (which was largely adopted).

**Comment by imatwork** [comment]
Confirmed working in 2.12.0. Thank you!
