### ISSUE TITLE
Does not work with ShadowDom/ShadowRoot.

### ISSUE THREAD

**Issue by blahblehblah** [1904labs/dom-to-image-more#86]
### Use case: description, code  

[jsfiddle](https://jsfiddle.net/IDisposable/emjL1ow8/)

### Browsers

- [ ] Chrome 49+  
- [ ] Firefox 45+

**Comment by IDisposable** [comment]
Looks like it works... what were you expecting it to look like?
![image](https://user-images.githubusercontent.com/874059/206060345-235415cf-1e2d-4545-9662-3eb408b2917b.png)

**Comment by meche-gh** [comment]
Managed to repro with v2.13.1 - https://jsfiddle.net/k7dfx3hy/. Doesn't throw an error but doesn't work either.

There's a nice example of shadow DOM in `relative-time` tags over at https://github.com/pulls.

Shadow DOM is meant to have a safe fallback for older browsers. This library clones the fallback but picks up styles like `width` and `height` for the rendered shadow root.
