### ISSUE TITLE
Not detecting unicode-range, loads all the font-faces

### ISSUE THREAD

**Issue by zoltanseer** [1904labs/dom-to-image-more#87]
When font-loading is made, does not care about `unicode-range` defined in the font-face and loads all available fonts. 

### Expected behavior
Should load only those which are loaded by the browser automatically

**Comment by meche-gh** [comment]
I suspect some elements might appear after a 2s delay in an animation, triggering a font load. Might be too many possible issues today

**Comment by zoltanseer** [comment]
At some point I will need to work on this, so I might open a PR if there is a solution. Thanks

**Comment by meche-gh** [comment]
Is this a large SVG? Would #92 be relevant?
