### ISSUE TITLE
`toSvg` regression for explicit CSS values equal to `inherit`

### ISSUE THREAD

**Issue by meche-gh** [1904labs/dom-to-image-more#90]
### Use case: description, code  

[jsfiddle](https://jsfiddle.net/8souw9nm/1/)

```html
<div id='dom-node'>
<span><a href='#dom-node'>dom-to-image-more/issues/90</a></span>
</div>

<div id='result'>
<img src='data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="232" height="132"><foreignObject x="0" y="0" width="100%" height="100%"><div id="dom-node" xmlns="http://www.w3.org/1999/xhtml" style="background-color: rgb(211, 211, 211); block-size: 100px; display: block; height: 100px; inline-size: 200px; padding-block: 16px; padding: 16px; padding-inline: 16px; text-align: center; width: 200px;">%0A<span><a href="%23dom-node" style="cursor: pointer; text-decoration-line: underline; text-decoration-thickness: initial;">dom-to-image-more/issues/90</a></span>%0A</div></foreignObject></svg>'></img>
</div>
```
```css
#dom-node {
  color: #000000;
  height: 100px;
  width: 200px;
  background-color: lightgrey;
  text-align: center;
  padding: 1em;
}

a[href="#dom-node"] {
  color: #000000;
}

#result {
  margin-top: 10px;
}
```

### Expected behavior

Related issues & PRs: #37 #71

It was taken as true that `unset` had no gotchas. I tried using `toSvg` on `.Box` in https://github.com/pulls. `copyUserComputedStyle`  is an over-eager optimisation and has value collisions. (I'm the author of #37 FWIW.)

In this case, link color overrides that match `inherit` (as in `.Box .Link--primary`) are stripped away prematurely.

Here's an explanation of the `copyUserComputedStyle` regression:
1. Initial value from user-agent origin = `-webkit-link`/`-moz-hyperlinktext`
2. Stylesheet from author origin sets it to an explicit color value, *which happens to be* the computed value of `inherit`
3. `copyUserComputedStyle` assigns `unset` inline which is computed as `inherit`
4. Because the computed value of `unset` and and the explicit color value match, that value is not added to the inline style
5. 👉 The output SVG's inline style has no explicit `color` style. So instead of `2`, we're literally back to square `1`. 😃

### Actual behavior (stack traces, console logs etc)

When you open up the `#result` image src from the jsfiddle demo, it appears purple.

### Library version

Regression confirmed in https://github.com/1904labs/dom-to-image-more/releases/tag/v2.12.0 and present since https://github.com/1904labs/dom-to-image-more/releases/tag/v2.9.1.

### Browsers

- [x] Chrome 49+
- [x] Firefox 45+

**Comment by meche-gh** [comment]
There's a small-but-still-there gotcha with the `iframe` approach. The `copyUserComputedStyleFast` method will also fail If the page doesn't allow creating iframes because of Trusted Types API.

Some ideas:
- Making `copyUserComputedStyleFast` a default
- new `copyUserComputedStyle` algorithm:
 - Set style attribute value to `all: unset;`
 - Get and cache default computed styles the same way
 - Compare and filter into `targetStyle`
- Make edited `copyUserComputedStyle` a fallback

**Comment by IDisposable** [comment]
Whoa, nice catch, sorry for not seeing this when first PRed. I'll introduce a regression test and make it pass :)  Seems your approach to the fast-path should work.

**Comment by IDisposable** [comment]
I'm addressing this in a new PR... would love to give credit on the package and readmd, but all I have is your github ID

**Comment by IDisposable** [comment]
Addressed this more completely in https://github.com/1904labs/dom-to-image-more/pull/91
