### ISSUE TITLE
Cannot get dynamic elements created by JavaScript

### ISSUE THREAD

**Issue by superthin** [1904labs/dom-to-image-more#93]
### Use case: description, code  

My DOM to save as:

```
<div id="mywrap" class="wrapper">
    <div class="layer1>My images / texts</div>
    <div class="layer2>My images / texts</div>
</div>
All layer is absolute with z-index as 1, 2, 3 => layer1, layer2, layer3.
My JavaScript code as...
let layer3 = document.createElement('div');
layer3.style.width = '100px';
layer3.style.height = '100px';
document.getElementById('mywrap').appendChild(layer3);
Layer3 is not show in created image.
```

### Expected behavior
The result must be included layer3

### Library version
05-07-2022
### Browsers

- [ ] Chrome 100+  
- [ ] Firefox 100+

**Comment by meche-gh** [comment]
Does layer3 contain text and/or styling?

**Comment by meche-gh** [comment]
Could you edit this JSFiddle - https://jsfiddle.net/4tshz2e3/4/ - to show us the issue?

**Comment by IDisposable** [comment]
I really appreciate you jumping in on these issues @meche-gh

**Comment by superthin** [comment]
Oh. It's working know. I don't know why. https://jsfiddle.net/superthin/p2y9w0gc/36/
Thank you guys for help!

**Comment by IDisposable** [comment]
The code fairy fixed this, closing.
