### ISSUE TITLE
ownerWindow is not defined 

### ISSUE THREAD

**Issue by jeannen** [1904labs/dom-to-image-more#94]
### Use case: description, code  
Hi!
I'm trying to install the package on my node.js app, but I'm not sure of how to do. I copied the content of /src/dom-to-image-more.js into my JS script (in the "public" folder), but whenever I try to use the default example:

var node = document.getElementById("h1");

```
domtoimage
  .toPng(node)
  .then(function (dataUrl) {
    console.log(dataUrl)
  })
  .catch(function (error) {
    console.error("oops, something went wrong!", error);
  });
```
I got an error saying ownerWindow is not defined.

I tried to use npm install and put `import domtoimage from "dom-to-image-more";` in my JS file but then I get an error when trying to use it (`<script src="/js/dom-to-img.js" type='module'></script>`):

Uncaught TypeError: Failed to resolve module specifier "dom-to-image-more". Relative references must start with either "/", "./", or "../".

I'm pretty new to this, so, not sure what's going on...

### Expected behavior
?

### Actual behavior (stack traces, console logs etc)
dom-to-img.js:475 Uncaught ReferenceError: ownerWindow is not defined
    at Object.getWindow (dom-to-img.js:475:79)
    at toSvg (dom-to-img.js:68:50)
    at draw (dom-to-img.js:205:16)
    at Object.toPng (dom-to-img.js:139:16)
    at <anonymous>:4:4

### Library version
2.13.1

### Browsers

- [X] Chrome 49+  
- [x] Firefox 45+

**Comment by meche-gh** [comment]
For getWindow the place where it says `|| ownerWindow` should be `|| global || window`. If someone could make a PR?

**Comment by IDisposable** [comment]
I'll do that tomorrow...

**Comment by IDisposable** [comment]
Going to cut a release with this and other changes today, but it's going to be (technically) a breaking change because of the changes to remove some long-unneeded stuff.

**Comment by meche-gh** [comment]
#100 would be a nice fold-in :)

**Comment by IDisposable** [comment]
Folded into v3.0.0-rc1

**Comment by IDisposable** [comment]
@bonzinho You can install v3.0.0-rc1 from NPM and see if that does the trick for you :)

**Comment by bonzinho** [comment]
Hi,  thanks for your help.
Now i have other problem " TypeError: invalid 'instanceof' operand t(...).HTMLCanvasElement" when a try download a .png with 
`domtoimage.toBlob(node).then(function (blob) {
        window.saveAs(blob, "node-image.png");
      });`

I dont know if you can helpme or may be i can open a new issue.
