### ISSUE TITLE
Tables where cell padding has been set to 0 lead to cropped/non-matching image

### ISSUE THREAD

**Issue by melink14** [1904labs/dom-to-image-more#95]
### Use case: description, code  

[jsfiddle](https://jsfiddle.net/4n52yzcg/)

In production, I have a large table and noticed that the bottom and left edges were cut off when saving to Png. Using fiddle I isolated the problem to setting the padding on table cells to 0.

In the fiddle the bottom edge is cut off and also the image is wider than the dom table so I guess there may be various small differences when padding is 0 in this case.

Seems related to https://github.com/1904labs/dom-to-image-more/issues/77 where the user also fixed the issue by adding padding. Tables naturally have 1px cell padding so this might not have been noticed in the general case.

![image](https://user-images.githubusercontent.com/1176550/210025510-05902204-5143-4a26-9e91-d10aadfbe79a.png)

### Expected behavior

Image should be full table.

### Actual behavior (stack traces, console logs etc)

Image doesn't match. Edges are cropped etc.

### Library version

2.13.0

### Browsers

- Chrome 108

**Comment by IDisposable** [comment]
@melink14 You can set the padding to `0.000001px` and it will work as expected :) It's a browser bug that I need to figure out how to report.

**Comment by IDisposable** [comment]
Also, there will be a new release in the v2 chain tomorrow... just finalizing a bit of cleanup.

**Comment by IDisposable** [comment]
See https://jsfiddle.net/4n52yzcg/119 for what that looks like (preview)

**Comment by meche-gh** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1406929

**Comment by meche-gh** [comment]
```javascript
domtoimage.toSvg(document.getElementById('mywrap'), { onclone: node => node.querySelectorAll('th, td').forEach(el => el.style.padding = '0px') })
  .then(function(dataUrl) {
    var img = new Image();
    document.getElementById('result').appendChild(img);
    img.src = dataUrl;
  })
  .catch(function(e) {
    console.log(e);
  })
```

**Comment by melink14** [comment]
> @melink14 You can set the padding to `0.000001px` and it will work as expected :) It's a browser bug that I need to figure out how to report.

Thanks for the work around!

**Comment by IDisposable** [comment]
Updated the jsfiddle https://jsfiddle.net/Lrgkwt5m/117/ to show the work-around, and also demo how use the `onclone` event to grab exactly what was cloned to pass to the SVG generator.

**Comment by zm-cttae** [comment]
It will be another 3-6 months for Chromium bug [#1406929](https://bugs.chromium.org/p/chromium/issues/detail?id=1406929) to land in peoples' devices (version target `111`).
